### PR TITLE
Install pkg dependencies using rosdep in melodic branch

### PR DESCRIPTION
**Pull request by iswariyam**
Rosdep is used to install the necessary ROS packages instead of using a list of packages in repository.debs

## Changelog
* setup.sh
* travis.yml
* dockerfile
* repository.rosinstall

## Related PRs
Related to #122 #123 

## Checklist:
- [x] My code doesn't contain unnecessary comment blocks (e.g. unused code, templates of `package.xml` or `CMakeLists.txt`)
- [x] I have updated the `package.xml` and `CMakeLists.txt` with the correct dependencies.

### CODE REVIEW

**Comment by iswariyam** [comment]
@sthoduka I have merged the latest version of kinetic branch with melodic because I had issues with rosdep due missing packages in mir_manipulation. As a result, I had to add exploration_server and explore_lite repos to respository.rosinstall because frontier_exploration and explore_lite (which are used in mir_2dnav) are not available as ROS packages for melodic.

**Comment by sthoduka** [comment]
> @sthoduka I have merged the latest version of kinetic branch with melodic because I had issues with rosdep due missing packages in mir_manipulation. As a result, I had to add exploration_server and explore_lite repos to respository.rosinstall because frontier_exploration and explore_lite (which are used in mir_2dnav) are not available as ROS packages for melodic.

ok, looks fine

@DharminB any idea whether these exploration packages have alternatives in melodic?

**Comment by DharminB** [comment]
> @DharminB any idea whether these exploration packages have alternatives in melodic?

Wiki for both the packages are only showing kinetic as their latest version. So I don't know. I don't think there would be alternatives, though.

**Comment by sthoduka** [comment]
ok I willl merge this then

**Pull request merged**
