### PR TITLE
Feature/empty space integration

### PR DESCRIPTION
**Pull request by RavisankarSelvaraju**
[

## Changelog

* Add empty space detector feature in place object server 
* ...

## Related PRs

Closes #XX  
Related to #YY

## Checklist:

- [x] My code doesn't contain unnecessary comment blocks (e.g. unused code, templates of `package.xml` or `CMakeLists.txt`)
- [x] I have updated the `package.xml` and `CMakeLists.txt` with the correct dependencies.
- [x] I have updated the documentation accordingly.

](https://github.com/RavisankarSelvaraju?tab=repositories)

### CODE REVIEW

**Comment by sthoduka** [comment]
you meant to keep the original `place_object_server.py`, right?

**Comment by RavisankarSelvaraju** [comment]
yes. i just want to add those new files in the same directory

**Comment by sthoduka** [comment]
ok, but it looks like both `place_object_server.py` and `place_object_server_empty_space.py` are the same in this PR.

**Comment by RavisankarSelvaraju** [comment]
Oh okay I changed the name and modified some comments in the new file. I think I have to replace the old file and then push again. On Jun 8, 2022 5:25 PM, Santosh Thoduka ***@***.***> wrote:
ok, but it looks like both place_object_server.py and place_object_server_empty_space.py are the same in this PR.

**Comment by sthoduka** [comment]
thanks!

**Pull request merged**
